### ISSUE TITLE
[Channels] Do you provide others RKE2 channel ?

### ISSUE THREAD

**Issue by Davidffry** [rancherfederal/rke2-ansible#101]
Hello,

As mentioned in the title, do you provision other rke2 channel (v1.22/v1.21...) as specified in vars file of the role rke_common?
I would like to install rancher web UI to manage the cluster **but** (at this moment) it seems impossible to install the UI because Rancher helm chart only supports the Kubernetes < v1.22.0 (as mentioned here : https://github.com/rancher/rancher/issues/34060#issuecomment-988222488   
![InkedMicrosoftTeams-image_LI](https://user-images.githubusercontent.com/31964077/146571497-334af3e0-e4f1-4472-b588-8bfaf4ea23bf.jpg)
)

So I test the v1.19, but it seems the env file is needed. I can't find any data about it.

Another issue: 
One of the tarball link is dead (in the docs), maybe you should remove it.

Thanks for the reply.

**Comment by aleiner** [comment]
You can install a specific version of RKE2 via this playbook. The compatibility with Rancher is documented here: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-3/
