### ISSUE TITLE
Adding Flux CD & SOPS

### ISSUE THREAD

**Issue by Robbilie** [rancherfederal/rke2-ansible#111]
Heyho,

awesome repo, currently using it to setup a small cluster at work at probably switching to using it instead of my terraformed rke cluster.

I am a huge gitops fan and so i added a flux cd role to a fork of this repo (and i will add another one for injecting a secret for sops support in flux).

I was wondering if you are interested in upstreaming this as an optional feature. Since this repo is a full playbook and not a role this would also help us/me greatly maintain our fork :P 

// Robert

**Comment by aleiner** [comment]
Hi @Robbilie - Flux and SOPS are both great tools but I'm afraid they are out of scope for what we're trying to accomplish with rke2-ansible.
