### ISSUE TITLE
Latest version breaks without defining rke2_common_yum_repo

### ISSUE THREAD

**Issue by aleiner** [rancherfederal/rke2-ansible#116]
Commit, 8b961f8d1f4877f3c8b31a88966a9ce8e01b0f6f, that allows you to specify a location for the yum repo for RKE2, doesn't have any default values for that path.  In an airgrap environment, this is fine since you have to specify a path regardless, but on an internet connected system, this should point to the latest version.

**Comment by mddamato** [comment]
fixed with #120
