### ISSUE TITLE
where do we define which version to install?

### ISSUE THREAD

**Issue by thinzaung** [rancherfederal/rke2-ansible#121]
Hi,  I am wondering how do we define INSTALL_RKE2_VERSION ? 

Thanks

**Comment by aleiner** [comment]
You can set the variable in a variety of places, such as group_vars/all:

---
install_rke2_version: v1.21.9+rke2r1

**Comment by BillKlineVT** [comment]
In case you see this and are doing a non-rpm-based install (i.e. tarball install for Ubuntu)... the variable `install_rke2_version` is not used... you have to specify`rke2_channel` and match ones of the existing channels at https://update.rke2.io/v1-release/channels

**Comment by mddamato** [comment]
The comments above seem to be correct. re-open if you continue to have a problem.
