### ISSUE TITLE
Add STIG'd hardening profile to Ansible

### ISSUE THREAD

**Issue by bgulla** [rancherfederal/rke2-ansible#128]
Add the STIG controls as a hardened-profile (similar to CIS-1.6) to the RKE2 ansible playbook. 

https://public.cyber.mil/announcement/disa-releases-the-rancher-government-solutions-rke2-security-technical-implementation-guide/

**Comment by CTFHCS** [comment]
i am super interested in this!

**Comment by jcox10** [comment]
From what I can tell there is nothing in the STIG that is not already covered by the CIS profiles.

**Comment by aleiner** [comment]
Please reach out to RGS (ranchergovernment.com) if you'd would be interested in this feature for your organization.
