### ISSUE TITLE
Support RHEL8 nftables

### ISSUE THREAD

**Issue by jcox10** [rancherfederal/rke2-ansible#134]
Iptables has been replaced with Nftables on RHEL8. The common role currently does not update any of the rules when only Nftables is installed. See [rh docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-nftables_configuring-and-managing-networking#automatically-loading-nftables-rules-when-the-system-boots_writing-and-executing-nftables-scripts) for more info.

**Comment by aceeric** [comment]
@jcox10 we may have some interest in this as well. Based on [this RKE2 guidance](https://docs.rke2.io/install/requirements#inbound-network-rules), for an out-of-the-box RKE2 install with Canal and no other CNI configurations it is possible to run these statements as a shell script on the cluster nodes with `nftables` and the `iptables` compatibility layer installed:
```
#!/usr/bin/env bash

# create a table
nft add table ip rke2

# create a base INPUT chain
nft add chain ip rke2 INPUT '{ type filter hook input priority 0 ; policy accept ; }'

# accept cluster CIDR source and dest
nft add rule rke2 INPUT ip daddr 10.42.0.0/16 accept
nft add rule rke2 INPUT ip saddr 10.42.0.0/16 accept
# RKE2 ports for out of the box Canal plus SSH and HTTPS
nft add rule rke2 INPUT meta l4proto tcp tcp dport 22          ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 443         ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 30000-32767 ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 2380        ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 2381        ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 2379        ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 10250       ct state new accept
nft add rule rke2 INPUT meta l4proto udp udp dport 8472        ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 6443        ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 9345        ct state new accept
nft add rule rke2 INPUT meta l4proto tcp tcp dport 9099        ct state new accept

# create a base FORWARD chain
nft add chain ip rke2 FORWARD '{ type filter hook forward priority 0 ; policy accept ; }'

# accept cluster CIDR source and dest
nft add rule rke2 FORWARD ip daddr 10.42.0.0/16 accept
nft add rule rke2 FORWARD ip saddr 10.42.0.0/16 accept

# create a base OUTPUT chain
nft add chain ip rke2 OUTPUT '{ type filter hook output priority 0 ; policy accept ; }'
```

This would produce the following `nftables` table/rules:
```
[root]# nft list table ip rke2
table ip rke2 {
        chain INPUT {
                type filter hook input priority filter; policy accept;
                ip daddr 10.42.0.0/16 accept
                ip saddr 10.42.0.0/16 accept
                tcp dport 22 ct state new accept
                tcp dport 443 ct state new accept
                tcp dport 30000-32767 ct state new accept
                tcp dport 2380 ct state new accept
                tcp dport 2381 ct state new accept
                tcp dport 2379 ct state new accept
                tcp dport 10250 ct state new accept
                udp dport 8472 ct state new accept
                tcp dport 6443 ct state new accept
                tcp dport 9345 ct state new accept
                tcp dport 9099 ct state new accept
        }

        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                ip daddr 10.42.0.0/16 accept
                ip saddr 10.42.0.0/16 accept
        }

        chain OUTPUT {
                type filter hook output priority filter; policy accept;
        }
}
```
Conceivably this rules file could be generated by Ansible using a Jinja template, and the cluster CIDR could be interpolated into the template like the current Rancher `iptables` Ansible does. To make it totally flexble it might need to have a way to be cognizent of the CNI that the installer selected so that it supported the various options RKE2 supports: Canal VXLAN, Cilium VXLAN, etc.

**HOWEVER** I notice in the existing [Rancher Ansible](https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_common/tasks/iptables_rules.yml) iptables task there are no DROP statements. So the Ansible appears to want to use IPTABLES to explicitly allow ports but - since there's no disallow - there's no effect. And in fact if I run that `nftables` script above which essentially mirrors the Ansible iptables logic, I'm not prevented from starting an HTTP server on some port  (e.g. "4444") and then accessing that HTTP server from another cluster node on "4444". So I'm wondering how the current Rancher Ansible is intended to be used in the first place without explicit DROPs...

**Comment by aleiner** [comment]
On EL8 systems, `iptables` can interact with `nftables`. On EL9, `iptables-nft` can serve the same purpose. I believe both are installed by default.

The issue with `nftables` with regard to using it as apart of rke2-ansible, is inability for a end-user to also supply their own ruleset, as a new table. This has been highlighted on this [page](https://superuser.com/questions/1787416/nftables-how-to-stop-further-chain-traversal-after-accept-verdict). Key point being that an `accept` doesn't stop processing the chain(s), allowing it to be squashed by any `drop`.


The rules needed for RKE2 are not the only rules that may be needed by a user. For this to work, all firewall rules would have to be passed to rke2-ansible. If an automation tool was used for configuring the OS, `nftables` management would be to be ignored there.

One potential work around would be to have variables for the table and chain name that we can then append rules to - default policy of `drop` and then a list of `accept` rules that rke2-ansible can add too. Another option is it leave what we have for the time being and prepare to shift to eBPF.

Was hoping to hear from @jcox10 and @aceeric on what their takes are. For those using rke2-ansible in an enterprise setting, ports for external scanners or logging tools need to be exposed which would normally be handled via a separate automation tool for OS configuration; or same tool, just different playbooks. I was hopeful that we could go with a separate table for rke2-ansible rules, but that doesn't appear possible.

cc: @mddamato @deiberts86

**Comment by aceeric** [comment]
Maybe it makes more sense to utilize Calico / Cilium in this area, depending on the CNI selected by the person installing RKE2.

**Comment by jcox10** [comment]
I am dangerous at best with iptables, so I'm probably not the best one to give guidance. We are running in more of a development scenario. What led me to file this issue is the ansible tasks for iptables were completely skipped on a RHEL8 system because [this](https://github.com/rancherfederal/rke2-ansible/blob/b1c8e65a900c5aee93a92e851059d5383d50b0e3/roles/rke2_common/tasks/main.yml#L65) when condition `ansible_facts.services["iptables.service"] is defined` is false, since the iptables service does not exist, but instead nftables does exist. However, maybe our systems are just missing a package?

**Comment by aleiner** [comment]
There is a package, iptables-services, but I'm not positive on how that works with nftables as the back end. It might just do a flush/import when you do a stop/start. I'll see if I can investigate.

**Comment by aleiner** [comment]
Thanks for confirming @jcox10. I'll close this ticket. EL9 and EL10 both will support eBPF which may be the more appropriate solution. But we have some time before needing to make that determination.
