### ISSUE TITLE
Repo fails ansible-lint

### ISSUE THREAD

**Issue by Daemonslayer2048** [rancherfederal/rke2-ansible#151]
This repo is currently failing ansible-lint. That should probably be corrected, at the same time the collections should probably be updated to the FQCNs as described here: https://ansible.readthedocs.io/projects/lint/rules/fqcn/
> We recommend you start using the fully-qualified collection name (FQCN) in your playbooks as the explicit and authoritative indicator of which collection to use as some collections may contain duplicate module names.

**Comment by Daemonslayer2048** [comment]
Upon further review in order to resolve `var-naming[no-role-prefix]` the three roles would need to be condensed into a single role. I think this is achievable but would require a much more lengthy discussion. I am going to create an MR to address the FQCN issue and a couple unrelated linting tasks.

**Comment by mddamato** [comment]
Should be fixed in #155

**Comment by Daemonslayer2048** [comment]
The linting issue is fixed in #151, I have my FQCN fix in #161 though.
