### ISSUE TITLE
Tarball deplyment failing while looking for yum repo

### ISSUE THREAD

**Issue by mkay2999** [rancherfederal/rke2-ansible#160]
new to Ansible, so sorry if I'm missing something basic here.  

But I'm testing for deploy in an offline environment with rke2-images.linux-amd64.tar.gz.  I place the file in the tarball_install directory but my deployment keeps erroring out with the following error:

TASK [rke2_common : YUM-Based | Install rke2-server] ******************************************************************************************************************************************
fatal: [10.10.2.128]: FAILED! => {"changed": false, "msg": "https://rpm.rancher.io/rke2/latest/common/centos/7Server/noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found\nTrying other mirror.\nTo address this issue please refer to the below knowledge base article \n\nhttps://access.redhat.com/articles/1320623\n\nIf above article doesn't help to resolve this issue please open a ticket with Red Hat Support.\n\n\n\n One of the configured repositories failed (Rancher RKE2 Common Latest),\n and yum doesn't have enough cached data to continue. At this point the only\n safe thing yum can do is fail. There are a few ways to work \"fix\" this:\n\n     1. Contact the upstream for the repository and get them to fix the problem.\n\n     2. Reconfigure the baseurl/etc. for the repository, to point to a working\n        upstream. This is most often useful if you are using a newer\n        distribution release than is supported by the repository (and the\n        packages for the previous distribution release still work).\n\n     3. Run the command with the repository temporarily disabled\n            yum --disablerepo=rke2-common ...\n\n     4. Disable the repository permanently, so yum won't use it by default. Yum\n        will then just ignore the repository until you permanently enable it\n        again or use --enablerepo for temporary usage:\n\n            yum-config-manager --disable rke2-common\n        or\n            subscription-manager repos --disable=rke2-common\n\n     5. Configure the failing repository to be skipped, if it is unavailable.\n        Note that yum will try to contact the repo. when it runs most commands,\n        so will have to try and fail each time (and thus. yum will be be much\n        slower). If it is a very temporary problem though, this is often a nice\n        compromise:\n\n            yum-config-manager --save --setopt=rke2-common.skip_if_unavailable=true\n\nfailure: repodata/repomd.xml from rke2-common: [Errno 256] No more mirrors to try.\nhttps://rpm.rancher.io/rke2/latest/common/centos/7Server/noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found\n", "rc": 1, "results": []}

any help would be appreciated

**Comment by aceeric** [comment]
@mkay2999 the air-gapped install can be run as follows:

1) Only the images file as you have done, and
2) The images **and** the RKE2 binary

In scenario 1, it still needs to install RKE2 and all you've provided is the image tarball - hence yum gets involved. In scenario 2, RKE2 is installed from the staged file in the `tarball_install` dir. Here's a manual way to stage the files in such a way as to initiate a fully-airgapped install:
```
export RKE2VER=v1.25.6 && export REL=rke2r1 &&\
curl -sfL https://github.com/rancher/rke2/releases/download/$RKE2VER%2B$REL/rke2-images.linux-amd64.tar.zst\
  -o ./tarball_install/rke2-images.linux-amd64.tar.zst &&\
  curl -sfL https://github.com/rancher/rke2/releases/download/$RKE2VER%2B$REL/rke2.linux-amd64.tar.gz\
  -o ./tarball_install/rke2.linux-amd64.tar.gz &&\
  curl -sfL https://github.com/rancher/rke2/releases/download/$RKE2VER%2B$REL/sha256sum-amd64.txt\
  -o ./tarball_install/sha256sum-amd64.txt
```
Hopefully this should get you going.

**Comment by mddamato** [comment]
@mkay2999 It is recommended that for an airgap installation, you host the rpms necessary inside your environment and then override the RPM repo configuration variables so that YUM can find the repo

**Comment by mddamato** [comment]
You can use the tarball installation as long as you have a mechanism to install container-selinux and rke2-selinux RPMs in the OS prior to the ansible playbook running. This generally works but is not an officially supported approach.

**Comment by mkay2999** [comment]
> @mkay2999 the air-gapped install can be run as follows:
> 
> 1. Only the images file as you have done, and
> 2. The images **and** the RKE2 binary
> 
> In scenario 1, it still needs to install RKE2 and all you've provided is the image tarball - hence yum gets involved. In scenario 2, RKE2 is installed from the staged file in the `tarball_install` dir. Here's a manual way to stage the files in such a way as to initiate a fully-airgapped install:
> 
> ```
> export RKE2VER=v1.25.6 && export REL=rke2r1 &&\
> curl -sfL https://github.com/rancher/rke2/releases/download/$RKE2VER%2B$REL/rke2-images.linux-amd64.tar.zst\
>   -o ./tarball_install/rke2-images.linux-amd64.tar.zst &&\
>   curl -sfL https://github.com/rancher/rke2/releases/download/$RKE2VER%2B$REL/rke2.linux-amd64.tar.gz\
>   -o ./tarball_install/rke2.linux-amd64.tar.gz &&\
>   curl -sfL https://github.com/rancher/rke2/releases/download/$RKE2VER%2B$REL/sha256sum-amd64.txt\
>   -o ./tarball_install/sha256sum-amd64.txt
> ```
> 
> Hopefully this should get you going.

yeah that solved it. thanks.
