### ISSUE TITLE
Add configuration to set specific RKE2 version

### ISSUE THREAD

**Issue by dorkamotorka** [rancherfederal/rke2-ansible#166]
ATM, as far as I know - one is unable to set a specific RKE2 version to be installed.

**Comment by getsomebread** [comment]
You can set a specific version if you use the tarball install method. The playbook will use this if you drop in the tar files of the version you want. In my automation flow, I'm doing something like this before running the site.yml playbook to achieve this:

```
rke2_install_version="v1.26.7+rke2r1"
git clone https://github.com/rancherfederal/rke2-ansible.git
cd rke2-ansible/tarball_install
export V=$( echo "$rke2_install_version" | sed 's/\+/%2B/' )
echo "Downloading $rke2_install_version install files"
wget -q https://github.com/rancher/rke2/releases/download/${V}/rke2.linux-amd64.tar.gz
wget -q https://github.com/rancher/rke2/releases/download/${V}/rke2-images.linux-amd64.tar.zst
```

**Comment by jcox10** [comment]
On RHEL you can install a specific version using this var:
`install_rke2_version: "v1.26.8+rke2r1"`

However, be aware that doing a `yum update` or `dnf update` will update the rpm to the latest patch version, which may not be what you want. Disabling the rke2 repos in `/etc/yum.repos.d` can prevent that behavior.
