### ISSUE TITLE
rke2 version check failing on bash pipe

### ISSUE THREAD

**Issue by getsomebread** [rancherfederal/rke2-ansible#167]
When installing a cluster (any rke2 version) to Rocky9 servers/agents from a Rocky9 host running ansible-core, install fails when doing a version check. Gets this failure:
```
TASK [rke2_common : Get tarball RKE2 version from temp location] ***************
fatal: [server2]: FAILED! => {"changed": false, "cmd": "set -o pipefail && /tmp/ansible.g76o0o12rke2-install.XXXXXXXXXX/bin/rke2 -v | head -n 1 | cut -d ' ' -f 3", "delta": "0:00:00.090148", "end": "2023-10-24 14:36:04.974730", "msg": "non-zero return code", "rc": 141, "start": "2023-10-24 14:36:04.884582", "stderr": "", "stderr_lines": [], "stdout": "v1.26.7+rke2r1", "stdout_lines": ["v1.26.7+rke2r1"]}
```

There are two lines with a bash pipe that result in this same error
- [previous_install.yml](https://github.com/rancherfederal/rke2-ansible/blob/7ae082dcaf3d485b4c2150ba0ad5338b35a8a00e/roles/rke2_common/tasks/previous_install.yml#L37)
- [tarball_install.yml](https://github.com/rancherfederal/rke2-ansible/blob/7ae082dcaf3d485b4c2150ba0ad5338b35a8a00e/roles/rke2_common/tasks/tarball_install.yml#L60)

I found [this useful link](https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q) that explains why this error happens. I successfully got the playbooks to run by replacing the lines linked above with this:
```
# previous_install.yml
-  ansible.builtin.shell: set -o pipefail && /usr/local/bin/rke2 -v | head -n 1 | cut -d ' ' -f 3
+  ansible.builtin.shell: set -o pipefail && /usr/local/bin/rke2 -v | awk '$1 ~ /rke2/ { print $3 }'

# tarball_install.yml
-      ansible.builtin.shell: set -o pipefail && {{ temp_dir.path }}/bin/rke2 -v | head -n 1 | cut -d ' ' -f 3
+      ansible.builtin.shell: set -o pipefail && {{ temp_dir.path }}/bin/rke2 -v | awk '$1 ~ /rke2/ { print $3 }'
```

I don't really know how to do a pull request, can you please update this?

**Comment by CharlesTollios** [comment]
@getsomebread  
I wasn't able to replicate an error code by running that command:
```
set -o pipefail && ./rke2 -v | head -n 1 | cut -d ' ' -f 3
```
However, I realized my /tmp directory is mounted with noexec and it may be preventing execution of rke2.
This may have to be re-written to handle that.

**Comment by GoldennDragonn** [comment]
I've got the same error on Ubuntu 22.04. After applying the suggested fix - the error was fixed. Thank you.
