### ISSUE TITLE
Add support for creating cluster with a load balancer / fixed registration address

### ISSUE THREAD

**Issue by Eric-Domeier** [rancherfederal/rke2-ansible#233]
As described in RKE2 Docs

https://docs.rke2.io/install/ha

Add capability to create cluster with a fixed address

**Comment by aleiner** [comment]
@Eric-Domeier - That functionality already exists:

https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_server/tasks/other_servers.yml#L27
https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_agent/tasks/main.yml#L34

Will that accomplish what you are looking for?

**Comment by Eric-Domeier** [comment]
> @Eric-Domeier - That functionality already exists:
> 
> https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_server/tasks/other_servers.yml#L27 https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_agent/tasks/main.yml#L34
> 
> Will that accomplish what you are looking for?

@aleiner Thanks for your reply.

The kubernetes_api_server_host var appears to be set to the first server in the hosts file in server group
https://github.com/rancherfederal/rke2-ansible/blob/95605817d28dcbbcd6419e3fdc1abc60cfee7a55/roles/rke2_agent/defaults/main.yml#L2

This does not achieve the HA setup described here: https://docs.rke2.io/install/ha

my changes implement the ability to specify fixed_registration_address variable which should be a valid DNS/IP to a configured load balancer described in the above docs. When defined it will use the fixed_registration_address variable on all servers after the first server, and then change the first server to point to the load balancer once the additional control plane nodes are up and running.

If the fixed_registration_address is not defined, it will continue to use the first server.

**Comment by aleiner** [comment]
`kubernetes_api_server_host` is a variable that can be passed in as a variable (all.yaml). If left unset, it defaults to the first server.

I use this to setup KubeVIP as a loadbalancer for the control plane.

**Comment by Eric-Domeier** [comment]
@aleiner 

Ahhh - that is a good point I did not think about. 

I will remove those changes

**Comment by aleiner** [comment]
Please test it to make sure it works for your use case. You might be doing something we haven't covered yet.

**Comment by Eric-Domeier** [comment]
@aleiner Sorry for the late reply.

I tested with your suggestion of using the kubernetes_api_server_host var in group vars and it was successful, Will push an updated PR and will close this issue
