### ISSUE TITLE
How to access the rancher dashboard?

### ISSUE THREAD

**Issue by TawfiqulBari** [rancherfederal/rke2-ansible#247]
Sorry, this is not an issue, just an convenience question. The cluster is deployed and i can access the cluster through kubectl. But still have no idea how to access the rancher dashboard. any help will be appreciated.

**Comment by R4tchi** [comment]
As far as i understand, this repository only install a RKE2 Cluster, not through Rancher.

**Comment by TawfiqulBari** [comment]
thanks !! makes sense !!

**Comment by TawfiqulBari** [comment]
I have installed Rancher in the RKE2 Cluster using Helm. And it works !! But i had to downgrade to version [v1.28.11-rc5+rke2r1], for Helm Stable chart for rancher to be installed (changing the right tar.gz files and put them into tarball_install directory). For anyone's reference, I have used the following links to do that,
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#customizing-your-ingress
https://helm.sh/docs/intro/quickstart/
