### ISSUE TITLE
Adding nodes to the cluster

### ISSUE THREAD

**Issue by TawfiqulBari** [rancherfederal/rke2-ansible#249]
Hello dear community. How to add new nodes to the cluster? do i have to add new nodes in the hosts file and re-run the playbook?

**Comment by aleiner** [comment]
Hi @TawfiqulBari - Yes, to add a new node, update you inventory to include the new server and/or agents. When you rerun Ansible, RKE2 should get installed and those nodes will get added to the cluster.

**Comment by TawfiqulBari** [comment]
Wow !! Thanks @aleiner that worked like a charm !!! thanks !!!

**Comment by aleiner** [comment]
Glad it worked. Please reach out if you have any other issues.
