### ISSUE TITLE
CIS hardening profile parse bug

### ISSUE THREAD

**Issue by hotsource59** [rancherfederal/rke2-ansible#262]
When using a current version of RKE2 like `v1.30.5+rke2r1` the CIS hardening is not applied, although it is set in `inventory/<mycluster>/group_vars/rke2_servers.yaml.

```yaml
rke2_config:
  profile: cis
```
This is recommended in the CIS hardening guide.

The code does not recognize a simple `cis` as profile and wants something like `cis-1.23`
https://github.com/rancherfederal/rke2-ansible/blob/058fd8324b020d9c2cfe2de2363239f18213f735/roles/rke2_common/tasks/cis-hardening.yml#L4

Using `cis-1.23` is not accepted by `v1.30.5+rke2r1` anymore. Starting the `rke2-server` results in 
```
level=fatal msg="cis-1.23 profile is deprecated. Please use 'cis' instead."
```

That behavior is also documented in the CIS hardening guide. Should I provide a pull request or will you fix this anytime soon?

**Comment by Daemonslayer2048** [comment]
Hey @hotsource59 we are actually moving towards a rewrite. I can confirm the rewrite we are working on works with the "CIS" profile. It should take fairly minimal changes on your end to switch over to that.

**Comment by jcox10** [comment]
This was already fixed in https://github.com/rancherfederal/rke2-ansible/pull/187, the regex can handle `cis` or `cis-1.23` depending on what version of rke2 you are installing.

**Comment by hotsource59** [comment]
Thanks for the fix. It's working now.
