### ISSUE TITLE
Enable kube-vip on-prem lb 

### ISSUE THREAD

**Issue by bgulla** [rancherfederal/rke2-ansible#28]
https://gist.github.com/bgulla/7a6a72bdc5df6febb1e22dbc32f0ca4f

**Comment by avsprashant** [comment]
Can this be added to ansible?

**Comment by aleiner** [comment]
kubevip can be deployed via ansible by making use of the `manifest_config_file_path` variable. kubevip can be precreated as a manifest (rbac + deployment) and automatically applied to RKE2.
