### ISSUE TITLE
Optionally use INSTALL_RKE2_ARTIFACT_PATH for rke2.linux with "Rancher RKE2 Common" yum repo for rke2-selinux

### ISSUE THREAD

**Issue by ron1** [rancherfederal/rke2-ansible#39]
Based on the directions taken by the Rancher system-upgrade-controller and the forthcoming Rancher 2.6 capi-based system-agent-installer-rke2, it seems the Rancher preference is to manage the rke2.linux self-extracting binary via a version-specific container image rather than a "Rancher RKE2 versioned" yum repo. However, on RHEL-based systems, it still seems to make sense to manage the rke2-selinux rpm via a "Rancher RKE2 Common" yum repo.

So, consider enabling use of the "Rancher RKE2 Common" yum repo separate from the "Rancher RKE2 versioned" yum repo. Also, handle configuration of selinux including yum installation of rke2-selinux package and enabling of selinux for containerd in config.yaml.

**Comment by mddamato** [comment]
I believe this has been implemented since you commented. Appreciate the feedback.

Please see: https://github.com/rancherfederal/rke2-ansible/blob/bfad4e53150b5ee8a4a976996d039e418df60035/roles/rke2_common/tasks/rpm_install.yml#L4-L31
