### ISSUE TITLE
Using the tarball installation method on Centos8 causes "Unable to watch for tunnel endpoints..." error

### ISSUE THREAD

**Issue by tposavitz-ccg** [rancherfederal/rke2-ansible#42]
**Description**
I am deploying a single-node RKE2 cluster using this ansible playbook. When using the air-gapped tarball installation method, I get the following error when running `kubectl get pods -A` :
```
The connection to the server was refused - did you specify the right host or port?
```
and when checking the system logs for rke2-server.service, I repeatedly see:
```
level=warning msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&resourceVersion=0&watch=true\": dial tcp 127.0.0.1:6443: connect: connection refused"
```

When deploying without the tarballs, I do not see this error. 

**Steps to Reproduce**
1. Clone the rke2-ansible repo onto what we'll call the "deployment VM".
2. Install and deploy a base Centos8 VM from any of the available mirrors: http://isoredirect.centos.org/centos/8/isos/x86_64/. We'll call this the "target VM". 
3. Make sure the target VM is reachable at a known IP from the deployment VM.
3. Configure passwordless SSH from your deployment VM onto the target VM. 
4. Configure passwordless sudo on the Centos8 VM for a user you control. We'll call them "test".
4.  Set the following values in inventory/sample/hosts.ini:
```
[rke2-servers]
{Insert IP of target VM} ansible_user=test

[rke2_cluster:children]
rke2_servers
```
7. Download v1.20.7+rke2r2 tarballs (`rke2-images.linux-amd64.tar.zst` and `rke2.linux-amd64.tar.gz`) from https://github.com/rancher/rke2/releases/tag/v1.20.7%2Brke2r2 and place them in tarball_install
8. Run the ansible playbook:
```
ansible-playbook site.yaml -i inventory/sample/hosts.ini
```
9. Copy the kubeconfig file from the traget VM to ~/.kube/config on your deployment VM:
```
ssh test@{insert target VM IP} "sudo cp /etc/rancher/rke2/rke2.yaml ~/.kube/config && sudo chown \$USER:\$USER ~/.kube/config
scp test@{insert target VM IP}:/~/.kube/config ~/.kube/config
```
10. Replace the loopback address in ~/.kube/config with the target VM IP.
11. Run `kubectl get pods -A`. You should get no response or the response shown in the description.
12. Access the target VM and run `sudo systemctl status rke2-server.service` to see the "Unable to watch..." message.

**Additional Detail**
RKE2 Version: 1.20.7+rke2r2
Possibly related to [this issue from the RKE2 repo.](https://github.com/rancher/rke2/issues/349)

**Comment by tposavitz-ccg** [comment]
Per https://github.com/rancherfederal/rke2-ansible/issues/41, there seems to be a typo in either the tarball_install README.md or the playbook. I tried downloading `rke2-images.linux-amd64.tar.gz` and leaving the playbook unmodified, which produced the same error described above. I tried changing references to `rke2-images.linux-amd64.tar.gz` in the playbook to `rke2-images.linux-amd64.tar.zst`, which produced the same error described above.

**Comment by 1naboki1** [comment]
I don't think that the issue is related with the tarball or image deployment. Got the same when deploying with selinux: true and cis-profile 1.6 on rhel8.4 (which is currently not supported).

After turning selinux off and restarting the services, it worked like charm

Check https://docs.rke2.io/install/requirements.html for CentOs

**Comment by tposavitz-ccg** [comment]
Ah, thanks for pointing out my silly mistake. I should've noticed that RKE2 only supports Centos 8.2. After rolling my Target VM back to CentOS 8.2 and disabling SELinux, everything runs as expected. I am testing now to see if installing the rke2-selinux RPM will result in the rke2 server running as expected, with SELinux enabled on the Target VM, per the instructions here: https://github.com/rancherfederal/rke2-ansible/blob/main/tarball_install/README.md
