### ISSUE TITLE
Question: Advertice node-ip ?

### ISSUE THREAD

**Issue by tburschka** [rancherfederal/rke2-ansible#43]
Hi,

First, thanks for this playbook. Since k3s has no support for GlusterFS, this is a very good alternative to k3sup. 

Now to my question: it's maybe a stupid question, i have a special setup where all hosts where in a public setup.
Therefore the given requirement was to use wireguard for all traffic between the hosts. . Also a level 4 proxy (haproxy) should be used for the api server. So ive created the following test setup

*server 1*
* public ip: 10.10.10.140
* wireguard_ip: 192.168.0.1
* additional hostnames: api.rke2.lb.local loadbalancer.rke2.lb.local
* os: ubuntu 20.04.2 LTS
* software: haproxy

*server 2*
* public ip: 10.10.10.141
* wireguard_ip: 192.168.0.2
* additional hostnames: server-01.rke2.lb.locall
* os: ubuntu 20.04.2 LTS

*server 3*
* public ip: 10.10.10.142
* wireguard_ip: 192.168.0.3
* additional hostnames: server-02.rke2.lb.local
* os: ubuntu 20.04.2 LTS

*server 4*
* public ip: 10.10.10.143
* wireguard_ip: 192.168.0.4
* additional hostnames: server-03.rke2.lb.local
* os: ubuntu 20.04.2 LTS

Every server knows the additonal hostnames of the other servers.

The HAProxy config looks like this:

```
global
    log /dev/log	local0
    log /dev/log	local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
    log	global
    mode	tcp
    option	dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend rke2_api
    bind :6443
    default_backend rke2_api_servers

backend rke2_api_servers
    server server-01 192.168.0.2:6443
    #server server-02 192.168.0.3:6443
    #server server-03 192.168.0.4:6443

frontend rke2_join
    bind :9345
    default_backend rke2_join_servers

backend rke2_join_servers
    server server-01 192.168.0.2:9345
    #server server-02 192.168.0.3:9345
    #server server-03 192.168.0.4:9345
```

server-02 and server-03 are disabled until the setup is done.

Now i've added the file `inventory/my-cluster/group_vars/all.yml`with the following content

```yaml
kubernetes_api_server_host: api.rke2.lb.local
```

So the registration will use the loadbalancer.

My hosts-ini has the following content:

```ini
[rke2_servers]
cluster-admin@10.10.10.141
cluster-admin@10.10.10.142
cluster-admin@10.10.10.143

[rke2_agents]

[rke2_cluster:children]
rke2_servers
rke2_agents
```

After running the playbook successfully, the output of `kubectl get nodes -o wide`  shows the folling content

```
NAME                STATUS   ROLES                       AGE   VERSION          INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
rke2-lb-server-01   Ready    control-plane,etcd,master   50m   v1.21.2+rke2r1   10.10.10.141   <none>        Ubuntu 20.04.2 LTS   5.4.0-77-generic   containerd://1.4.4-k3s2
rke2-lb-server-02   Ready    control-plane,etcd,master   46m   v1.21.2+rke2r1   10.10.10.142   <none>        Ubuntu 20.04.2 LTS   5.4.0-77-generic   containerd://1.4.4-k3s2
rke2-lb-server-03   Ready    control-plane,etcd,master   47m   v1.21.2+rke2r1   10.10.10.143   <none>        Ubuntu 20.04.2 LTS   5.4.0-77-generic   containerd://1.4.4-k3s2
```

So during the registration the public ip was used instead of  the wireguard ip. The log of the Loadbalancer also show no traffic on port 6443.  Is it possible to modify this? Is this the option `--node-ip` during start? Is it possible to make this configurable in the playbook?

My current setup has no agents jet, but is there the same problem there?

**Comment by tburschka** [comment]
i managed the change of the internal ip by this small changes:

hosts.ini
```ini
[rke2_servers]
cluster-admin@10.10.10.141 node_ip=192.168.0.2
cluster-admin@10.10.10.142 node_ip=192.168.0.3
cluster-admin@10.10.10.143 node_ip=192.168.0.4

[rke2_agents]

[rke2_cluster:children]
rke2_servers
rke2_agents
```

roles/rke2_common/tasks/config.yml
```yaml
- name: Add node-ip
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "node-ip: {{ hostvars[inventory_hostname].node_ip }}"
  when: hostvars[inventory_hostname].node_ip is not undefined
```

(A little feature request: wouldn't it be nice if all args would be able to set like this via config?)


But now, i' stuck at the next point. The traffic (from outside) is forwarded to the first server.
My kubetoken instead came from another server:


```
Jul  2 23:22:08 loadbalancer-01 haproxy[9726]: Connect from 192.168.0.3:55300 to 192.168.0.1:9345 (rke2_join/TCP)
Jul  2 23:22:08 loadbalancer-01 haproxy[9726]: Connect from 192.168.0.3:55308 to 192.168.0.1:9345 (rke2_join/TCP)
Jul  2 23:22:08 loadbalancer-01 haproxy[9726]: Connect from 192.168.0.3:55312 to 192.168.0.1:9345 (rke2_join/TCP)
Jul  2 23:31:38 loadbalancer-01 haproxy[9726]: Connect from 10.10.10.38:55742 to 10.10.10.140:6443 (rke2_api/TCP)
Jul  2 23:31:38 loadbalancer-01 haproxy[9726]: Connect from 10.10.10.38:55743 to 10.10.10.140:6443 (rke2_api/TCP)
Jul  2 23:31:38 loadbalancer-01 haproxy[9726]: Connect from 10.10.10.38:55744 to 10.10.10.140:6443 (rke2_api/TCP)
Jul  2 23:31:38 loadbalancer-01 haproxy[9726]: Connect from 10.10.10.38:55745 to 10.10.10.140:6443 (rke2_api/TCP)
Jul  2 23:31:38 loadbalancer-01 haproxy[9726]: Connect from 10.10.10.38:55746 to 10.10.10.140:6443 (rke2_api/TCP)
```


so im not able to connect (yet) to connect from outside:

```shell
$ kubectl get nodes
Unable to connect to the server: x509: certificate is valid for 10.43.0.1, 127.0.0.1, 10.10.10.141, 192.168.0.2, 10.43.0.1, not 10.10.10.140
```

**Comment by mddamato** [comment]
@tburschka Thank you for bringing this to our attention. We currently have another issue that I think will solve your problem #58 take a look at this and add any details there.
