### ISSUE TITLE
NetworkManager fix

### ISSUE THREAD

**Issue by dgvigil** [rancherfederal/rke2-ansible#48]
Add a task to check if NetworkManager is running and apply the fix.
https://docs.rke2.io/known_issues/#networkmanager

**Comment by dgvigil** [comment]
As well...
> In some operating systems like **RHEL 8.4, NetworkManager** includes two extra services called nm-cloud-setup.service and nm-cloud-setup.timer. These services add a routing table that interfere with the CNI plugin's configuration. Unfortunately, there is no config that can avoid that as explained in the issue. Therefore, **if those services exist, they should be disabled and the node must be rebooted**.

**Comment by mddamato** [comment]
should be addressed in #54

**Comment by mddamato** [comment]
in #54
