### ISSUE TITLE
EL8 minimal install doesn't include tar

### ISSUE THREAD

**Issue by cstackpole** [rancherfederal/rke2-ansible#55]
When testing on a minimal install of EL8 (RHEL and CentOS), tar isn't included which means I ended up with an error:

```
fatal: [192.168.1.155]: FAILED! => {"changed": false, "cmd": "tar -xf /tmp/ansible.gwik8e25rke2-install.XXXXXXXXXX/rke2.linux-amd64.tar.gz -C /usr/local", "msg": "[Errno 2] No such file or directory: b'tar': b'tar'", "rc": 2}
```

It would be nice if tar was on the list for ansible to check/install or have it on the pre-requirements list.

Thanks!

**Comment by mddamato** [comment]
@tuckcodes #74 I decided to just do it

**Comment by JPerkster** [comment]
This appears to be solved. Closing
