### ISSUE TITLE
Urls should be variabalized for easier configuration change during deployments

### ISSUE THREAD

**Issue by FruityWelsh** [rancherfederal/rke2-ansible#57]
Many organizations have internal repos for holding packages and images and may block outside usage, making these variables would allow for easier switching during deployments of updates as urls change, as well as removing environment specific data from the code.

**Comment by mddamato** [comment]
Maybe we could consider allowing for full rpm repo overriding in addition to parameterizing just the URLs used in them. This could also allow things like local repos, resigned packages, unverifiable packages, etc.

**Comment by aleiner** [comment]
The entire yum repo can be configured via:
rke2_common_yum_repo
and
rke2_versioned_yum_repo

If you're changing the repo URL, we assume you're also going to need to either disable the GPG check or change the GPG key location.
