### ISSUE TITLE
Add a good rke2_config: example to the README.md

### ISSUE THREAD

**Issue by dgvigil** [rancherfederal/rke2-ansible#61]
A good example of what can be put in the `rke2_config:` would be a nice add to the README.md

**Comment by mddamato** [comment]
@dgvigil I was thinking about this and decided to leave it out of #54 purely to not introduce even more to the refactor. I also thought it might make sense to add more than one sample to include multiple common scenarios.

**Comment by dgvigil** [comment]
It's fine to have kept it out of the refactor, but I think it's important to give good examples of proper use in the README.md and I think your default is a good example.

**Comment by FathiQ** [comment]
Simple example
```
rke2_config:
  #debug: false
  profile: cis-1.5
  etcd-snapshot-retention: 21
  selinux: true
  tls-san:
  - my-kube.example.com
  - my-cluster.example.com
  node-taint: CriticalAddonsOnly=true:NoExecute
  cni: calico
```

**Comment by mddamato** [comment]
In the RKE2 terraform repository there is a sample section that describes a couple of scenarios, I'd like to approach similar to that and have a few common host.ini examples. The scenario described above, for example, is incomplete because if you specify `CriticalAddonsOnly=true:NoExecute` without an accompanying agent config without that taint then nginx will spin on unschedulable.

**Comment by FathiQ** [comment]
Hi @mddamato my example for the server correct me if I'm wrong I'm using this to disallow scheduling pods on master/control plane nodes and create pods only on workers/agents.

**Comment by kphunter** [comment]
I would benefit from a more comprehensive set of configuration options in the `sample>group_vars>...` folder. I had to dig to find out that a setting that was previously used [has been deprecated](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/):
```
# kubelet-arg
rke2_kubelet_args:
  - "feature-gates=DynamicKubeletConfig=false"
```
And although I really appreciate this playbook (thanks!), it's difficult know exactly what has changed without a release (and notes) or a changelog.

**Comment by mddamato** [comment]
@kphunter There is a sample group config at `inventory/sample/group_vars/rke2_servers.yml`

```
# Primary RKE2 server configuration parameters. Remove the curly braces ( {} ) and add your configuration.
# See https://docs.rke2.io/install/install_options/server_config/ for all configuration options.
rke2_config: {}
  # debug: false
```

We were trying to imply that all the RKE2 options can be set here. For example, as you requested above this would be set with:

```
rke2_config:
  kubelet-arg:
    - "feature-gates=DynamicKubeletConfig=false"
```

Let us know if any options set in this way do not work properly. I apologize for the quick change around this functionality, it is still a fairly new project and is not getting as much development attention as we would like.
