### ISSUE TITLE
Latest refactor PR breaks Ubuntu builds

### ISSUE THREAD

**Issue by tuckcodes** [rancherfederal/rke2-ansible#65]
Customer reported that the latest refactor breaks Ubuntu builds due to a couple of breaking changes. Customer reported the following recommendations to remediate:

1. Move tarball code code from RPM -> Tarball ansible file
2. In tarball ansible file remove all delegate_to 127.0.01

**Comment by mddamato** [comment]
1 - #54 rearranged some tarball stuff and #66 was also added to tarball install section

2 - I believe this is likely due to ansible config containing default root user for localhost.

@tuckcodes can you confirm and close this issue if no longer a problem?

**Comment by dgvigil** [comment]
ping @tuckcodes

**Comment by tuckcodes** [comment]
Customer got back saying that 2 is still an issue for him. Customer suggested that we remove the delegate_to entirely and that it isn't necessary. I will bring this up during tomorrow's standup to discuss further.

**Comment by mddamato** [comment]
#73

**Comment by tuckcodes** [comment]
Confirmed it is resolved.
