### ISSUE TITLE
Add to ansible-galaxy

### ISSUE THREAD

**Issue by bsecker** [rancherfederal/rke2-ansible#68]
Hi guys, 

I've been playing around with this project a bit and am impressed with it. It works well in isolation, but because of the structure of this repository, to get the roles integrated into an existing ansible repo I had to manually copy the `roles/` out and paste them into our repo. 
I would like to open some discussion around restructuring the repo so that it can be easily imported into [ansible-galaxy](https://galaxy.ansible.com/), for easier integration into customers existing infrastructure repositories.

Would something like that be possible? Hope what I'm asking for makes sense, would be happy to clarify.

**Comment by mddamato** [comment]
This has floated around some and I think the approach so far has been to have a separate repository that extracts the roles from this repository and gets combined with other roles such as the OS STIG/RKE2 prep roles being developed to make them more galaxy friendly. This might have already been done, in fact. I'll see if we can gather some info around this.

**Comment by bsecker** [comment]
Hey @mddamato, do you have any updates on your above comment? 

Cheers

**Comment by dgvigil** [comment]
That was my original goal with this repo [example](https://github.com/rancherfederal/rke2-ansible/pull/1#issuecomment-788921502). It was meant to be a single play, but other decisions were made and this was turned into a full playbook.

Perhaps we can see about turning this back into a single role and see if the community agrees with us, @bsecker .

**Comment by dgvigil** [comment]
Looking over the code base again, this would be a herculean effort to return the code base to a single role. I *really* like the idea, but not sure how feasible it is now.

**Comment by slconley** [comment]
rather than reverse back a single role, what about using this repo for a galaxy collection?  possibly even consider bringing in the rke2_nvidia role from the enable-gpu-rke2 repo.  I have done some offline work along these lines and this would be very straight-forward to do.  I would be glad to help make this happen.

**Comment by Robbilie** [comment]
https://github.com/lablabs/ansible-role-rke2

that repository does provide a role, was there any communication between the maintainers of this repo and theirs?

**Comment by jdloft** [comment]
How about https://github.com/jdloft/rke2-ansible/tree/galaxy? That would be the bare minimum for being able to import playbooks:
```yaml
- import_playbook: rancherfederal.rke2.site
```
