### ISSUE TITLE
Failed: this task 'ansible.builtin.command' has extra param

### ISSUE THREAD

**Issue by cstackpole** [rancherfederal/rke2-ansible#69]
Greetings,
Testing out some of the latest changes and ran into an issue that I thought I would report.
```
$ git log -1
commit 1fc0e3694c3ae4749d29d0a314ce1a65507b27e6 (HEAD -> main, origin/main, origin/HEAD)
Author: Mike D'Amato <7297973+mddamato@users.noreply.github.com>
Date:   Fri Aug 6 13:31:40 2021 -0400

    Tarball needs agent service installation (#66)
 ```

Deploying from a Ubuntu 20.04 fully updated system to three VM's all Rocky 8.4 and fully updated (1 server; two agents)

```
$ ansible-playbook --version
ansible-playbook 2.9.6
  config file = ~/Code/Github_RancherFederal_rke2-ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

```
$ ansible-playbook site.yml -i inventory/my-cluster/hosts.ini -K
[snip]
TASK [rke2_server : Setup initial server] **************************************************************************************************
fatal: [192.168.1.54]: FAILED! => {"reason": "this task 'ansible.builtin.command' has extra params, which is only allowed in the following modules: add_host, meta, shell, include, script, win_command, import_tasks, set_fact, include_role, win_shell, include_vars, import_role, include_tasks, command, group_by, raw\n\nThe error appears to be in '~/Code/Github_RancherFederal_rke2-ansible/roles/rke2_server/tasks/first_server.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Wait for kubelet process to be present on host\n  ^ here\n"}

```

There is no wait that I can tell. It get's to this spot and immediately errors out.

Thoughts?
Thanks!

**Comment by mddamato** [comment]
I believe this is due to ansible version <2.10 and the `ansible.builtin.` part not being parsed correctly. @cstackpole Do you have a hard requirement to use 2.9?

**Comment by cstackpole** [comment]
Unfortunately, I do. From Ubuntu to RHEL, the approved OS/software stack for me only has 2.9. I can not pip install the latest version in my environment.

Per the ansible documentation https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-rhel-centos-or-fedora :

> Since Ansible 2.10 for RHEL is not available at this time, continue to use Ansible 2.9.

If the code base is now using newer then 2.9, can you please update the README?
>Deployment environment must have Ansible 2.9.0+

**Comment by mddamato** [comment]
That is very fair. We will retest on 2.9 and make any necessary modifications. Thanks @cstackpole

**Comment by cstackpole** [comment]
Yup! That seems to have fixed it. Thank you!
