### ISSUE TITLE
Add pofile cis-1.5 after initial rollout

### ISSUE THREAD

**Issue by tburschka** [rancherfederal/rke2-ansible#76]
Hi, 

i've setup a cluster before the greater rework was done. The second cluster i've setup was after the rework. But i didn't saw, that `profile: cis-1.5` wasn't default anymore. Is there any documention how to enable this after inital setup?

Thanks!

**Comment by dgvigil** [comment]
You can add the CIS profile after the cluster has been deployed, but you will need to update the PSPs.
https://docs.rke2.io/security/hardening_guide/#podsecuritypolicies
