### ISSUE TITLE
systemctl start fails causing fail on ansible run

### ISSUE THREAD

**Issue by jberger** [rancherfederal/rke2-ansible#79]
In my manual attempts to deploy rke2, I often would get failure return codes from `systemctl start ...`. Because of the way the restart logic is written the service appears to fail and restart several times during initialization. While that logic is beyond the scope of this project, I wonder if perhaps failures could be ignored during the start tasks in the role(s)?

**Comment by mddamato** [comment]
@jberger Could you elaborate on the conditions required to observe the failure and which type of nodes you're seeing this for? We have tried to work in enough staggering logic where each "start" happens in sequence and the systemd unit then waits until ETCD has joined to return exit 0.

**Comment by jberger** [comment]
I don't think this is related to staggering. Even when doing the deploy manually (without the ansible stuff) sometimes the initial `systemctl start rke2-server.service` exits 1. It then continues to retry until it works. Mostly I think this is due to round-robin DNS for the registration url. Anyway, the logic later on in ansible seems to be fine for detecting that the kubelet and etcd come up it just is noise that the start shows as an error.

Anyway, if you need any other details I'm happy to give them. Ubuntu 20.04, rke2 latest. Baremetal servers.

**Comment by lee-b** [comment]
It would be good not to expect systemd here at all.  systemd is 1m+ lines of code, not really fit for purpose on a small lean server that just wants to run rke.  For these and other reasons, Devuan (debian/ubuntu compatible in all other ways) doesn't include it, and instead provides options of sysvinit, runit, etc.

**Comment by aleiner** [comment]
We are unable to replicate any issues with rke2 starting. Feel free to open a new ticket if you're still experiencing issues.
