### ISSUE TITLE
Cannot set other than rke2-images.linux-amd64.tar.(gz|zst) with tarball_install method

### ISSUE THREAD

**Issue by sebastienmusso** [rancherfederal/rke2-ansible#82]
In tarball_install method, container image could only be rke2-images.linux-amd64.tar.zst or rke2-images.linux-amd64.tar.gz.

We are currently using cilium cni in some of our cluster and would like to import zipped images from rke2 project without having to use registry as done with default rke2 images

Proposed change:
https://github.com/rancherfederal/rke2-ansible/pull/83

**Comment by aleiner** [comment]
This can be accomplished via the `rke2_images_urls` array. Supply a path to the URL and it will be included.
