### ISSUE TITLE
Tarball install w/SELinux enforcing fails

### ISSUE THREAD

**Issue by ron1** [rancherfederal/rke2-ansible#86]
Environmental Info
RKE2 Version: v1.20.10+rke2r1
[root@ip-10-11-12-13 rke2]# rke2 -v
rke2 version v1.20.10+rke2r1 (a4f6020)
go version go1.16.6b7

Node(s) CPU architecture, OS, and Version
Just one server node
[root@ip-10-11-12-13 rke2]# uname -a
Linux ip-10-11-12-13.donut.org 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[root@ip-10-11-12-13 rke2]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

Cluster Configuration
One server node

Describe the bug
rke2-server v1.20.10 tarball install on CentOS 7.9 w/SELinux enforcing fails to start w/flag --selinux

See issue https://github.com/rancher/rke2/issues/1865 for more information including reproduction details.

**Comment by dgvigil** [comment]
@ron1 To help me better troubleshoot this can you please explain the use case for adding the rke2 repo, but doing the tarball install?

**Comment by ron1** [comment]
It is currently convenient for us to use a rke2 common yum repo just to yum install the rke2-selinux rpm. This rpm is rke2 version agnostic and has a much slower change lifecycle than rke2. Note, we could have just as easily installed this rpm using the rpm utility instead of yum.

Also we don't like the idea of SUC modifying a binary that is already being managed by a yum repo.

Does that answer yout question.

**Comment by dgvigil** [comment]
I can understand the concern with the versioning moving at what may seem like an indiscriminate pace.  To ensure that all systems are using a specific version would it be acceptable to still use the Rancher RKE2 repos, but be able to pin the desired version of rke2, rke2-selinux, and kubernetes?  These can be variables for all three.

This would ensure that this ansible playbook does not install anything beyond your desired version, even if run multiple times or used to add new nodes.

Would that address your major concerns, @ron1?

**Comment by ron1** [comment]
We have found that working with yum repos in an airgapped environment is very inconvenient. Tarballs are much easier for us to import and integrate into our IaC solution.

**Comment by ron1** [comment]
The current rke2-ansible Air-Gap doc page makes no mention of the selinux restriction identified by this issue. Is that an oversight? Also, is it a realistic expectation that air-gapped environments mirror all the rancher yum repos needed for a successful yum-based install? Task file https://github.com/rancherfederal/rke2-ansible/blob/3bd706ec02a5ee900174bbb1750ede4f3a3ec249/roles/rke2_common/tasks/rpm_install.yml is air-gap unfriendly in that it hard-codes multiple internet urls including 
https://update.rke2.io/v1-release/channels/ as well as multiple rancher yum repo baseurls. How is this supposed to work?

**Comment by mddamato** [comment]
- Tarball installs do not implement the necessary selinux modules like the RPMs do, proper way would be to use RPMs on these types of systems or turn off selinux enforcement.
- The URLs mentioned in these comments do not apply when the user supplies the correct airgap variables. Please refer to the readme and the sample inventory files for examples on how to provide your own URLs for air gapped installations.

Closing this ticket for now @ron1, but if you have this issue with more recent versions of this please don't hesitate to open a new ticket with your concerns
